name:               "Kotet"
description:        "Kotetのブログ。<wbr/>興味分野の<wbr/>知識を<wbr/>まとめたり、<wbr/>翻訳したり<wbr/>している。"

url:                "https://kotet.github.io" # for Twitter card
author:             "Kotet"
email:              "kotet0418@gmail.com"
gravatar_hash:
twitter:            "kotetttt"
pinterest:
linkedin:
facebook:           "kazutoshi.ban.7"

google_analytics: UA-88180620-1

twitter_cards: on
twitter_username: kotetttt

repository: kotet/kotet.github.io

disqus_shortname:

baseurl:            ""

markdown:           kramdown

sass:
  style:            :compressed

gems:
  - jekyll-sitemap