baseURL: "https://kotet.jp"
languageCode: "ja"

title: "Kotet's Personal Blog"

params:
    description: "Kotetのサイト。主にブログ。"

taxonomies:
  tag: "tags"

permalinks:
  blog: /:year/:month/:day/:filename

pygmentsCodeFences: true
hasCJKLanguage: true