version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo
    working_directory: ~/project
    steps:
      - checkout
      - run:
          command: |
            HUGO_ENV=production hugo --minify

  deploy:
    docker:
      - image: cibuilds/hugo
    working_directory: ~/project
    steps:
      - run:
          command: |
            mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            rm -rf public/
            git clone git@github.com:kotet/kotet.github.io.git public
            HUGO_ENV=production hugo --minify
            cd public
            echo "blog.kotet.jp" > CNAME
            git config --global user.name "CircleCI"
            git config --global user.email "circleci@example.com"
            git add --all
            git commit -m "${CIRCLE_BRANCH} (Circle CI)"
            git push git@github.com:kotet/kotet.github.io.git master

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build
